# Generated by Django 4.2.6 on 2023-10-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_room_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=100, verbose_name="general"),
        ),
    ]
