# Generated by Django 4.2.6 on 2023-10-30 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_room_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="online",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
