version: '3.4'

# NOTE: When connecting to the postgres docker container in the web interface,
# try using 'postgres' as the host name instead of 'localhost' or 'host.docker.internal'

# NOTE 2: Copy this file in the same directory as 'docker-compose.yml' file and use your own credentials

services:
  web:
    build: .
    image: sova
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres-user'
      POSTGRES_DB: 'sova_db'
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
